### ISSUE TITLE
Application CR created won't work as helm chart is not published on a git repository

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-argocd#35]
## Issue

The Application CR created won't work when deployed on a cluster as the helm chart generated is not available under `.helm` but instead under `./target` folder which is of course not published on the git repository

```
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: .helm/kubernetes/code-with-quarkus
    repoURL: https://github.com/ch007m/code-with-quarkus.git
```

@iocanel

**Comment by iocanel** [comment]
The install command, is meant to warn users about it. 
If this is not the case then it should be considered a bug.

**Comment by cmoulliard** [comment]
I will close this ticket as I think that this is not the responsibility of the argocd extension to check/verify if manifests: helm chart, yaml files, etc have been pushed on a git repository from the path specified: 
```
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .helm/kubernetes/code-with-quarkus
    repoURL: https://github.com/ch007m/code-with-quarkus.git
```
@iocanel
