### ISSUE TITLE
Wrong repo URL created

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-argocd#68]
## Issue

If the git repository is defined as such `git remote add origin https://$GITEA_TOKEN@gitea.cnoe.localtest.me:8443/quarkus/my-quarkus-hello.git` then the repoUrl of the ArgoCD application generated is wrong as it replaces the symbol `:` with `/` between the server name and the port

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-quarkus-hello
  namespace: user1
spec:
  destination:
    namespace: user1
    server: https://kubernetes.default.svc
  project: my-quarkus-hello
  source:
    helm:
      valueFiles:
      - values.yaml
    path: .helm/kubernetes/my-quarkus-hello
    repoURL: https://gitea.cnoe.localtest.me/8443/quarkus/my-quarkus-hello.git // ERROR
    targetRevision: HEAD
```

**Comment by cmoulliard** [comment]
The issue is coming from how the git url is sanitized by dekorate: https://github.com/dekorateio/dekorate/blob/main/core/src/main/java/io/dekorate/utils/Git.java#L134-L145

![Image](https://github.com/user-attachments/assets/0cb4e716-8f5b-42d8-9ddf-d281c7fcd70d)

**Comment by iocanel** [comment]
The utility should take the protocol into consideration. If it's http(s) then `@` and `:` are meant to be basic auth delimiters. if we have a `git@github.com` then it has different meaning and we should keep on doing what we currently do.

**Comment by cmoulliard** [comment]
So, let's do the change until now (to test it) within the argocd project and maybe backport it next to Dekorate

**Comment by cmoulliard** [comment]
Token or username:password should not be declared part of the Applicationn > spec > source > `repoURL` but using a secret  

See: https://www.redhat.com/en/blog/how-to-use-argocd-deployments-with-github-tokens

Example
```
echo "apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitea.cnoe.localtest.me:8443/quarkus/my-quarkus-hello.git
  password: ed1....6500b
  username: not-used" | k apply -f -
```
