### ISSUE TITLE
Review the logic about how we generate the AppProject

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-argocd#70]
## Improvement

Review the existing logic about how we generate the Argo CD resource:  `AppProject`

Argo CD supports different use cases depending if a `default` project exists, if the option `Application(s) in any namespace or not is [enabled](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#applications-in-any-namespace). 

1. Default project

If a default `AppProject` resource [exists](https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#the-default-project), then the user could use it or we could also generate it (to be checked if this is needed)

Most of the time such a default project is configured to allow `Applications` to be created from `Any` git  repositories, to `Any` kubernetes cluster(s) and where All the resources could be deployed. See: https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#projects

```
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
```

2. New AppProject

If no `default` project exists then the user should be able to generate an `AppProject` resource. But in this case it should be created under the namespace of the Argo CD control's space: `argocd` or `openshift-gitops`

```
apiVersion: argoproj.io/v1alpha1
metadata:
  name: <APP_PROJECT_NAME>
  namespace: <ARGOCD_CONTROL_PLANE_NAMESPACE> // argocd OR openshift-gitops OR user's project control plane namespace
spec:
  sourceRepos:
  - <QUARKUS_APP_GIT_SCM>
  destinations:
  - namespace: <ARGOCD_CONTROL_PLANE_NAMESPACE> // argocd OR openshift-gitops OR user's project control plane namespace
    server: <KUBERNETES_SERVER_SERVICE> // https://kubernetes.default.svc or "*" or another Cluster API Address
``` 

2. With Any namespace

As discussed [here](https://github.com/argoproj/argo-cd/issues/21150#issuecomment-2573561167), the AppProject resource should be always created under the Argo CD control plane's namespace no matter where Argo CD `Applications` will be created: `ns1`, `ns2`, etc

Nevertheless, it is needed also in this case to add the parameter: `sourceNamespaces` as discussed here: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#allowing-additional-namespaces-in-an-appproject

```
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: <APP_PROJECT_NAME>
  namespace: <ARGOCD_CONTROL_PLANE_NAMESPACE> // argocd OR openshift-gitops OR user's project control plane namespace
spec:
  sourceRepos:
  - <QUARKUS_APP_GIT_SCM>
  destinations:
  - namespace: <APPLICATION_NAMESPACE>
    server: <KUBERNETES_SERVER_SERVICE> // https://kubernetes.default.svc or "*" or another Cluster API Address
  sourceNamespaces:
  - <APPLICATION_NAMESPACE>
```
